# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

strategy:
  matrix:
    linux_jdk_10:
      imageName: "ubuntu-16.04"
      jdk_version: "1.10"
    linux_jdk_11:
      imageName: "ubuntu-16.04"
      jdk_version: "1.11"
    windows_jdk_10:
      imageName: "vs2017-win2016"
      jdk_version: "1.10"
    windows_jdk_11:
      imageName: "ubuntu-16.04"
      jdk_version: "1.11"
  maxParallel: 2

pool:
  vmImage: $(imageName)

jobs:
  - job: "BuildJob"
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(jdk_version)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
