# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

strategy:
  matrix:
    linux_jdk_10:
      imageName: "ubuntu-16.04"
      jdk_version: "1.10"
    linux_jdk_11:
      imageName: "ubuntu-16.04"
      jdk_version: "1.11"
    windows_jdk_10:
      imageName: "vs2017-win2016"
      jdk_version: "1.10"
    windows_jdk_11:
      imageName: "ubuntu-16.04"
      jdk_version: "1.11"
  maxParallel: 2

pool:
  vmImage: $(imageName)

jobs:
- template: ../steps/java.maven.yml
  parameters: 
    jdk_version: $(jdk_version)    
- job: TestCoverage
  steps:
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "JaCoCo"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
      failIfCoverageEmpty: true